#!/usr/bin/python
from bitcoinrpc.authproxy import AuthServiceProxy
import jsonrpc
import time

access = AuthServiceProxy("http://RPCUSER:RPCPASSWORD@127.0.0.1:RPCPORT")
info = access.getinfo()
peer = access.getpeerinfo()
mine = access.getmininginfo()
stake = access.getstakinginfo()
balance = access.getbalance()
check = access.checkwallet()

ff = open('/var/www/html/index.html', 'w')

ff.write("<!DOCTYPE html>")
ff.write("<html>")
ff.write("<head>")
ff.write("<link rel='stylesheet' href='styles.css'>")
ff.write("</head>")
ff.write("<body>")
ff.write("<div class='container-base'>")
ff.write("<div class='title'>")
ff.write("<h1> YOUR COINS NAME <br\></h1>")
ff.write("</div>")
ff.write("<div class='box'>")
ff.write("<h2>")
ff.write("Balance: " + str(info['balance']) + "<br \>\n")
ff.write("</h2>")
ff.write("</div>")
ff.write("<div class='container'>")
ff.write("Last Update: " + time.strftime("%H:%M:%S %Y-%m-%d") + "<br \>\n")
ff.write("This Nodes: " + str(info['ip']) + "<br \>\n")
ff.write("addnode=" + str(peer[1]['addr']) + "<br \>\n")
ff.write("addnode=" + str(peer[3]['addr']) + "<br \>\n")
ff.write("addnode=" + str(peer[4]['addr']) + "<br \>\n")
ff.write("addnode=" + str(peer[5]['addr']) + "<br \>\n")
ff.write("addnode=" + str(peer[2]['addr']) + "<br \>\n")
ff.write("addnode=" + str(peer[0]['addr']) + "<br \>\n")
ff.write("Connections: " + str(info['connections']) + "<br \>\n")
ff.write("</div>")
ff.write("<div class='container-a'>")
ff.write("Block Height: " + str(info['blocks']) + "<br \>\n")
ff.write("Wallet Check Passed: " + str(check['wallet check passed']) + "<br \>\n")
ff.write("Staking Active: " + str(stake['staking']) + "<br \>\n")
ff.write("New Mint: " + str(info['newmint']) + "<br \>\n")
ff.write("Unconfirmed Stake: " + str(info['stake']) + "<br \>\n")
ff.write("Diff: " + str(stake['difficulty']) + "<br \>\n")
ff.write("Weight: " + str(stake['weight']) + "<br \>\n")
ff.write("Net Stake Weight: " + str(stake['netstakeweight']) + "<br \>\n")
ff.write("Expected Time Till Stake: " + str(stake['expectedtime']) + "<br \>\n")
ff.write("</div>")
ff.write("</div>")
ff.write("</body>")
ff.write("</html>")
ff.close()

ff = open('/var/www/html/styles.css', 'w')

ff.write(".container{")
ff.write("display: inline;")
ff.write("float: left;")
ff.write("background: #333;")
ff.write("color: white;")
ff.write("box-shadow: 3px 3px 50px #000;")
ff.write("padding: 2%;")
ff.write("width: 38%;")
ff.write("border: 3px double #fff;")
ff.write("margin: 3%;")
ff.write("font-size: 18px;")
ff.write("}")
ff.write("")
ff.write(".container-a{")
ff.write("display: inline;")
ff.write("float: right;")
ff.write("background: #333;")
ff.write("color: white;")
ff.write("box-shadow: 3px 3px 50px #000;")
ff.write("padding: 2%;")
ff.write("width: 38%;")
ff.write("border: 3px double #fff;")
ff.write("margin: 3%;")
ff.write("font-size: 18px;")
ff.write("}")
ff.write("")
ff.write("body{")
ff.write("text-align: center;")
ff.write("color: #eee;")
ff.write("background-color: #777;")
ff.write("}")
ff.write("")
ff.write(".box{")
ff.write("box-shadow: 3px 3px 50px #000;")
ff.write("width: 90%;")
ff.write("padding: 8px;")
ff.write("color: #0f0;")
ff.write("border: 3px double #fff;")
ff.write("background-color: #333;")
ff.write("margin-left: auto;")
ff.write("margin-right: auto;")
ff.write("}")
ff.write("")
ff.write(".container-base{")
ff.write("display: inline;")
ff.write("float: left;")
ff.write("background: #333;")
ff.write("color: white;")
ff.write("box-shadow: 3px 3px 50px #000;")
ff.write("padding: 8px;")
ff.write("width: 40%;")
ff.write("border: 3px double #fff;")
ff.write("margin: 10px;")
ff.write("}")
ff.write("")
ff.close()
